<section id="contentSection">
	<div class="content">
		<div class="indexLeft">
			<img class="book" src="<?php echo IMAGE;?>6STcover.jpg" width=150 height=200 alt="preview eBook Six Strange Tales" title="preview eBook Six Strange Tales" border=0 align="left" />
			<a href="http://www.amazon.com/dp/B006GRZ0D8" target="_blank"><img class="burst" src="cdn/images/burstOrderNow.png" width=82 height=82 alt="On Sale Now" title="On Sale Now" border=0 align="left" /></a>
			<div class="googleLike">
				<iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2Fpages%2FSix-Strange-Tales%2F275946239119864&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font=trebuchet+ms&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:80px; height:21px;" allowTransparency="true"></iframe>
				<a class="a2a_dd" href="http://www.addtoany.com/share_save"><img src="http://static.addtoany.com/buttons/favicon.png" width="16" height="16" border="0" alt="Share"/></a>
			</div>
		</div>
		<div class="indexInfo">
			<h1>1 Million Kindles Sold Per Week!</h1>
			<p>Amazon has recently reported upward sales of Kindles trending into popular culture,
				it's quick on the go reading. <br />This is a fast paced world, let's take time out to slow it down some.
				<br /> Treat yourself to a new book today.</p>

			<h1>Best Noir Literature in recent History!</h1>
			<p>Individual Eleven has created a masterpiece for your enjoyment. 
				<br />These are his dreams and nightmares come to life.</p>

			<h1>Learn how to get a copy - FREE!!!</h1>
			<p>Primary Kindle customers can get an advanced copy for free. <b><a href="http://www.amazon.com/dp/B006GRZ0D8">LEARN HOW</a></b>. 
				<br />Limited time offer.</p>
				
			<form id="mixtapeButton" action="<?php echo URL; ?>cdn/audio/6ST_soundtrack.zip" method="POST">
				<button>Download promotional 6ST mixtape - FREE</button>
			</form>
		</div>
	</div>
</section>   