	<footer role="footer">
		<div id="footer">
			<ul>
				<li><a href="<?php echo $this->baseUrl()?>/">Home</a>&nbsp; &bull; &nbsp;</li>
				<li><a href="http://www.youtube.com/user/SixStrangeTales?feature=watch" target="_blank">Video</a>&nbsp; &bull; &nbsp;</li>
				<li><a href="http://www.amazon.com/dp/B006GRZ0D8" target="_blank">Kindle</a>&nbsp; &bull; &nbsp;</li>
				<li><a href="http://www.noveltysoundbytes.com" target="_blank">nSb</a>&nbsp; &bull; &nbsp;</li>
				<li><a href="http://www.barnesandnoble.com/w/six-strange-tales-individual-eleven/1107867933?ean=2940013454415&itm=1&usri=six+strange+tales" target="_blank">Barnes &amp; Nobles</a>&nbsp; &bull; &nbsp;</li>
				<li id="contact">Contact</li>
			</ul>
			<p>Six Strange Tales courtesy of nSb publishing, LLC, Amazon.com, Barnes &amp; Nobles<br />&copy; Copyright 2012 All rights reserved</p>
		</div>
		<canvas id="canvas" width="900" height="60"></canvas>
	</footer>
	
	
	 
  <!-- JavaScript - DEV -->
  <script src="<?php echo $this->baseURL('cdn/jQuery/jQuery.js'); ?>"></script>
  
  <!-- JavaScript - PROD -->
  <script src="<?php //echo $this->baseURL('../cdn/jQuery/jQuery.js'); ?>"></script>
  <script type="text/javascript" src="http://static.addtoany.com/menu/page.js"></script> <!-- Google+ social share -->
  
    <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js" type="text/javascript"></script>
    <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->
  
  <!-- JavaScript -->
	