  <nav role="navigation">
    <div id="nav">
    	<ul class="navItems">
    		<li><a href="<?php echo $this->baseUrl();?>/">HOME</a></li>
    		<li><a href="<?php echo $this->baseUrl();?>/about">ABOUT</a></li>
    	</ul>
      <a href="http://www.youtube.com/user/SixStrangeTales?feature=watch" target="_blank"><img src="<?php echo IMAGE;?>socialMedia/youtube_logo.png" width=20 height=20 border=0 alt="Check out our channel on youTube" title="Check out our channel on youTube" /></a>
      <a href="http://bl157w.blu157.mail.live.com/default.aspx?rru=compose%3fsubject%3d<? echo EMAIL_SUBJECT;?>&body=<? echo EMAIL_BODY;?>&nwi=1&n=1890483940" target="_blank"><img src="<?php echo IMAGE;?>socialMedia/msn.png" width=21 height=20 border=0 alt="<? echo EMAIL_TITLE;?>" title="<? echo EMAIL_TITLE;?>" /></a>
      <a href="http://us.mg4.mail.yahoo.com/neo/launch?.rand=118204780&action=compose&Subj=<? echo EMAIL_SUBJECT;?>&Body=<? echo EMAIL_BODY;?>" target="_blank"><img src="<?php echo IMAGE;?>socialMedia/yahoo.png" width=20 height=20 border=0 alt="<? echo EMAIL_TITLE;?>" title="<? echo EMAIL_TITLE;?>" /></a>
      <a href="https://mail.google.com/mail/?ui=2&view=cm&fs=1&tf=1&su=<? echo EMAIL_SUBJECT;?>&body=<? echo EMAIL_BODY;?>%2F%0D%0A%0D%0A%0D%0A%0D%0A--%0D%0ASent%20via%20http%3A%2F%2Fwww.sixstrangetales.com" target="_blank"><img src="<?php echo IMAGE;?>socialMedia/gmail.png" width=27 height=20 border=0 alt="<? echo EMAIL_TITLE;?>" title="<? echo EMAIL_TITLE;?>" /></a>
      <a href="http://www.barnesandnoble.com/w/six-strange-tales-individual-eleven/1107867933?ean=2940013454415&itm=1&usri=six+strange+tales" target="_blank"><img src="<?php echo IMAGE;?>socialMedia/nook-icon.png" width=20 height=20 border=0 alt="Now available on Nook" title="Now available on Nook" /></a>
	  	<a href="http://www.amazon.com/dp/B006GRZ0D8" target="_blank"><img src="<?php echo IMAGE;?>socialMedia/kindle-icon.png" width=20 height=20 border=0 alt="Available on Kindle" title="Available on Kindle" /></a>
      <a href="http://www.facebook.com/dialog/send?app_id=123050457758183&link=http://www.amazon.com/dp/B006GRZ0D8&redirect_uri=http://www.example.com/response" target="_blank"><img src="<?php echo IMAGE;?>socialMedia/facebook.png" width=20 height=20 border=0 alt="Like us on Facebook" title="Like us on Facebook" /></a>
      <a href="https://twitter.com/intent/tweet?source=tweetbutton&text=<? echo TWEET; ?>&url=<? echo URL_KINDLE; ?>" target="_blank"><img src="<?php echo IMAGE;?>socialMedia/twitter.png" width=28 height=20 border=0 alt="Twitter" title="Tweet about it" /></a>
      <a href="http://noveltysoundbytes.com" target="_blank"><img src="<?php echo IMAGE;?>nSb.gif" width=20 height=20 border=0 alt="nSb publishing, LLC" title="nSb publishing, LLC" /></a>
    </div>
  </nav>