<section role="error">
	<div class="content error">
	  <h1>Oops, there's a problem here...</h1>
	  <h2><?php echo $this->message ?></h2>
	  <p>Here's a link to get you back on track: <a href="http://www.sixstrangetales.com">CLICK HERE</a></p>
	
	  <?php if (isset($this->exception)): ?>
	  
	  <h3>Exception information:</h3>
	  <p>
	      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
	  </p>
	
	  <h3>Stack trace:</h3>
	  <pre><?php echo $this->exception->getTraceAsString() ?>
	  </pre>
	
	  <h3>Request Parameters:</h3>
	  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
	  </pre>
	
	  <?php endif ?>
	</div>
</section>
