<section id="contentSection">
	<div class="content">
		<article>
			<div class="contentLeft">
				<h1>About Individual Eleven</h1>
				<p>Individual Eleven is a rare breed of author. This work was created when he decided that he would write down his bad dreams at night. Through that process he concocted some of the darkest stories driven by the depths and inner demons of one human mind.</p>
				<p>Actually Eleven got his start as a musician later transitioning into the world of film and television producing what he calls artistic renditions of other peoples greed. Writing has been an off and on love affair which eventually turned into a passion as this particular project developed. Once stating, 'I think this book is going to be pretty good' he stepped outside of himself and immersed into these characters which started out as an amalgam of different dreams, thought and ideas into one complex and coherent title 'Six Strange Tales'.</p> 
				<p>His roots trace back to an old Indian reservation in Shinnecock Hills, NY. Later in his adult life he moved to California where much of his family moved to and scattered across the state. He's a bit of a recluse so it's difficult to get him to go out into the public eye as he feels he's entertained the masses anonymously for years and would like to continue doing so. Writing is therapeutic for Eleven. </p>
				<p>Currently their is no planned book tour but Eleven has stubbornly agreed to participate in social media forums which he previously decided he would never do. Hopefully the 'masses' bring him out of his shell.</p>
			</div>
		</article>
		<?php include_once 'rightSide.phtml'; ?>
	</div>
</section>