<aside>
	<div class="contentRight twoColumn">
		<a href="http://www.amazon.com/dp/B006GRZ0D8"><img class="book" src="<?php echo IMAGE;?>6STcover.jpg" width=150 height=200 border=0 alt="Six Strange Tales eBook" title="Six Strange Tales eBook" /></a>
		<h2>ON SALE NOW!!</h2>
		<ul class="about">
			<li class="readMore">Read more...</li>
			<li><a href="<?php echo URL;?>about/">About Six Strange Tales</a></li>
			<li><a href="<?php echo URL;?>about/author/">About the Author</a></li>
			<li><a href="<?php echo URL;?>about/story/">About the Stories</a></li>
		</ul>
		<div class="googleLike">
			<iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2Fpages%2FSix-Strange-Tales%2F275946239119864&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font=trebuchet+ms&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:80px; height:21px;" allowTransparency="true"></iframe>
			<a class="a2a_dd" href="http://www.addtoany.com/share_save"><img src="http://static.addtoany.com/buttons/favicon.png" width="16" height="16" border="0" alt="Share"/></a>
		</div>
		</div>
</aside>