<section id="contentSection">
	<div class="content">
		<article>
			<div class="contentLeft">
				<h1>About the Stories</h1>
				<p>Author, Individual Eleven, actually had these nightmares, wrote them down at dusk, elaborated and shared them with all of us. The book touches on subject matter such as gore and violence, mystery, sex, purgatory, the dangers of drug abuse and even androgyny. </p>
				<p>The act opens during the college years of a group of friends and evolves into the background of one poor soul as we engage with their vulnerabilities and strength in 'Oh, Tammy'. Next we enter the home life of Neicy to discover a sick and twisted web of deceit and morbid trickery. As you thumb through the pages of these stories imagine a man having these disturbing dreams and then letting the world in on his grimmest fears. Six Strange Tales will have you questioning the neighbor, family and even your own moral fiber.</p>
			</div>
		</article>
		<?php include_once 'rightSide.phtml'; ?>
	</div>
</section>